from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QIntValidator, QIcon
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QTableWidgetItem, QMessageBox, QAbstractItemView, QPushButton
import numpy as np
def table_contains_noninteger_values(table):
    for i in range(table.rowCount()):
        for j in range(table.columnCount()):
            item = table.item(i, j)
            if item is not None:
                try:
                    int(item.text())
                except ValueError:
                    error_message = "Erreur: Vous avez saisie une valeur non entière. "
                    QMessageBox.warning(table, "Error", error_message)
                    return True
    return False
class MatriceWindow(object):
    def calculatrice(self):
        from calculatrice import Ui_MainWindow
        self.window1 = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window1)
        self.window1.show()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(610, 900)
        MainWindow.setMinimumSize(QtCore.QSize(610, 900))
        MainWindow.setMaximumSize(QtCore.QSize(610, 900))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(233, 243, 253);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 590, 891))
        self.tabWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.label_3 = QtWidgets.QLabel(self.tab_1)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_1)
        self.tableWidget.setGeometry(QtCore.QRect(0, 90, 280, 280))
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(55)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(55)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(55)
        self.tableWidget.verticalHeader().setMinimumSectionSize(55)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_1)
        self.tableWidget_2.setGeometry(QtCore.QRect(290, 90, 280, 280))
        self.tableWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_2.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_2.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_2.setRowCount(5)
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setObjectName("tableWidget_2")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.tableWidget_2.horizontalHeader().setVisible(False)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(55)
        self.tableWidget_2.horizontalHeader().setHighlightSections(True)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(55)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(55)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(55)
        self.label_4 = QtWidgets.QLabel(self.tab_1)
        self.label_4.setGeometry(QtCore.QRect(300, 60, 81, 16))
        self.label_4.setObjectName("label_4")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_1)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 500, 280, 280))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_3.sizePolicy().hasHeightForWidth())
        self.tableWidget_3.setSizePolicy(sizePolicy)
        self.tableWidget_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_3.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_3.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_3.setRowCount(5)
        self.tableWidget_3.setColumnCount(5)
        self.tableWidget_3.setObjectName("tableWidget_3")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.tableWidget_3.horizontalHeader().setVisible(False)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(55)
        self.tableWidget_3.horizontalHeader().setHighlightSections(True)
        self.tableWidget_3.horizontalHeader().setMinimumSectionSize(55)
        self.tableWidget_3.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.tableWidget_3.verticalHeader().setDefaultSectionSize(55)
        self.tableWidget_3.verticalHeader().setMinimumSectionSize(55)
        self.tableWidget_3.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.label_5 = QtWidgets.QLabel(self.tab_1)
        self.label_5.setGeometry(QtCore.QRect(10, 470, 81, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.tab_1)
        self.pushButton.setGeometry(QtCore.QRect(230, 400, 130, 40))
        self.pushButton.setCursor(Qt.PointingHandCursor)
        self.pushButton.setStyleSheet("""
                                                        QPushButton {
                                                            border: none;
                                                            color: rgb(80, 138, 198);
                                                            background-color: rgb(162, 208, 250);
                                                            border-radius:3px;}
                                                        QPushButton:hover {
                                                            background-color:  rgb(80, 138, 198);
                                                            color:  rgb(162, 208, 250);}
                                                            """)
        self.pushButton.setObjectName("pushButton")
        self.spinBox_14 = QtWidgets.QSpinBox(self.tab_1)
        self.spinBox_14.setGeometry(QtCore.QRect(190, 10, 70, 40))
        self.spinBox_14.setMinimum(1)
        self.spinBox_14.setMaximum(5)
        self.spinBox_14.setProperty("value", 5)
        self.spinBox_14.setObjectName("spinBox_14")
        self.label_32 = QtWidgets.QLabel(self.tab_1)
        self.label_32.setGeometry(QtCore.QRect(10, 20, 130, 21))
        self.label_32.setObjectName("label_32")
        self.spinBox_15 = QtWidgets.QSpinBox(self.tab_1)
        self.spinBox_15.setGeometry(QtCore.QRect(500, 10, 70, 40))
        self.spinBox_15.setMinimum(1)
        self.spinBox_15.setMaximum(5)
        self.spinBox_15.setProperty("value", 5)
        self.spinBox_15.setObjectName("spinBox_15")
        self.label_33 = QtWidgets.QLabel(self.tab_1)
        self.label_33.setGeometry(QtCore.QRect(300, 20, 150, 21))
        self.label_33.setObjectName("label_33")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.spinBox_27 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_27.setGeometry(QtCore.QRect(190, 10, 70, 40))
        self.spinBox_27.setMinimum(1)
        self.spinBox_27.setMaximum(5)
        self.spinBox_27.setProperty("value", 5)
        self.spinBox_27.setObjectName("spinBox_27")
        self.label_57 = QtWidgets.QLabel(self.tab_2)
        self.label_57.setGeometry(QtCore.QRect(300, 20, 150, 21))
        self.label_57.setObjectName("label_57")
        self.spinBox_28 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_28.setGeometry(QtCore.QRect(500, 10, 70, 40))
        self.spinBox_28.setMinimum(1)
        self.spinBox_28.setMaximum(5)
        self.spinBox_28.setProperty("value", 5)
        self.spinBox_28.setObjectName("spinBox_28")
        self.tableWidget_23 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_23.setGeometry(QtCore.QRect(0, 500, 280, 280))
        self.tableWidget_23.setEditTriggers(QAbstractItemView.NoEditTriggers)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_23.sizePolicy().hasHeightForWidth())
        self.tableWidget_23.setSizePolicy(sizePolicy)
        self.tableWidget_23.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_23.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_23.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_23.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_23.setRowCount(5)
        self.tableWidget_23.setColumnCount(5)
        self.tableWidget_23.setObjectName("tableWidget_23")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_23.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_23.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_23.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_23.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_23.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_23.setHorizontalHeaderItem(2, item)
        self.tableWidget_23.horizontalHeader().setVisible(False)
        self.tableWidget_23.horizontalHeader().setDefaultSectionSize(55)
        self.tableWidget_23.horizontalHeader().setHighlightSections(True)
        self.tableWidget_23.horizontalHeader().setMinimumSectionSize(55)
        self.tableWidget_23.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_23.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_23.verticalHeader().setVisible(False)
        self.tableWidget_23.verticalHeader().setDefaultSectionSize(55)
        self.tableWidget_23.verticalHeader().setMinimumSectionSize(55)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(300, 60, 81, 16))
        self.label_10.setObjectName("label_10")
        self.label_58 = QtWidgets.QLabel(self.tab_2)
        self.label_58.setGeometry(QtCore.QRect(10, 470, 81, 16))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.tab_2)
        self.label_59.setGeometry(QtCore.QRect(10, 20, 130, 21))
        self.label_59.setObjectName("label_59")
        self.tableWidget_24 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_24.setGeometry(QtCore.QRect(290, 90, 280, 280))
        self.tableWidget_24.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_24.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_24.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_24.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_24.setRowCount(5)
        self.tableWidget_24.setColumnCount(5)
        self.tableWidget_24.setObjectName("tableWidget_24")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_24.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_24.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_24.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_24.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_24.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_24.setHorizontalHeaderItem(2, item)
        self.tableWidget_24.horizontalHeader().setVisible(False)
        self.tableWidget_24.horizontalHeader().setDefaultSectionSize(55)
        self.tableWidget_24.horizontalHeader().setHighlightSections(True)
        self.tableWidget_24.horizontalHeader().setMinimumSectionSize(55)
        self.tableWidget_24.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_24.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_24.verticalHeader().setVisible(False)
        self.tableWidget_24.verticalHeader().setDefaultSectionSize(55)
        self.tableWidget_24.verticalHeader().setMinimumSectionSize(55)
        self.tableWidget_25 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_25.setGeometry(QtCore.QRect(0, 90, 280, 280))
        self.tableWidget_25.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_25.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_25.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_25.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_25.setRowCount(5)
        self.tableWidget_25.setColumnCount(5)
        self.tableWidget_25.setObjectName("tableWidget_25")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_25.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_25.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_25.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_25.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_25.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_25.setHorizontalHeaderItem(2, item)
        self.tableWidget_25.horizontalHeader().setVisible(False)
        self.tableWidget_25.horizontalHeader().setDefaultSectionSize(55)
        self.tableWidget_25.horizontalHeader().setHighlightSections(True)
        self.tableWidget_25.horizontalHeader().setMinimumSectionSize(55)
        self.tableWidget_25.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_25.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_25.verticalHeader().setVisible(False)
        self.tableWidget_25.verticalHeader().setDefaultSectionSize(55)
        self.tableWidget_25.verticalHeader().setMinimumSectionSize(55)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_11.setGeometry(QtCore.QRect(230, 400, 130, 40))
        self.pushButton_11.setCursor(Qt.PointingHandCursor)
        self.pushButton_11.setStyleSheet("""
                                                        QPushButton {
                                                            border: none;
                                                            color: rgb(80, 138, 198);
                                                            background-color: rgb(162, 208, 250);
                                                            border-radius:3px;}
                                                        QPushButton:hover {
                                                            background-color:  rgb(80, 138, 198);
                                                            color:  rgb(162, 208, 250);}
                                                            """)
        self.pushButton_11.setObjectName("pushButton_11")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_26 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_26.setGeometry(QtCore.QRect(0, 540, 280, 280))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_26.sizePolicy().hasHeightForWidth())
        self.tableWidget_26.setSizePolicy(sizePolicy)
        self.tableWidget_26.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_26.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_26.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_26.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_26.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_26.setRowCount(5)
        self.tableWidget_26.setColumnCount(5)
        self.tableWidget_26.setObjectName("tableWidget_26")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_26.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_26.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_26.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_26.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_26.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_26.setHorizontalHeaderItem(2, item)
        self.tableWidget_26.horizontalHeader().setVisible(False)
        self.tableWidget_26.horizontalHeader().setDefaultSectionSize(55)
        self.tableWidget_26.horizontalHeader().setHighlightSections(True)
        self.tableWidget_26.horizontalHeader().setMinimumSectionSize(55)
        self.tableWidget_26.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_26.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_26.verticalHeader().setVisible(False)
        self.tableWidget_26.verticalHeader().setDefaultSectionSize(55)
        self.tableWidget_26.verticalHeader().setMinimumSectionSize(55)
        self.label_60 = QtWidgets.QLabel(self.tab_3)
        self.label_60.setGeometry(QtCore.QRect(10, 510, 81, 16))
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.tab_3)
        self.label_61.setGeometry(QtCore.QRect(10, 20, 150, 21))
        self.label_61.setObjectName("label_61")
        self.tableWidget_27 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_27.setGeometry(QtCore.QRect(290, 140, 280, 280))
        self.tableWidget_27.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_27.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_27.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_27.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_27.setRowCount(5)
        self.tableWidget_27.setColumnCount(5)
        self.tableWidget_27.setObjectName("tableWidget_27")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_27.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_27.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_27.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_27.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_27.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_27.setHorizontalHeaderItem(2, item)
        self.tableWidget_27.horizontalHeader().setVisible(False)
        self.tableWidget_27.horizontalHeader().setDefaultSectionSize(55)
        self.tableWidget_27.horizontalHeader().setHighlightSections(True)
        self.tableWidget_27.horizontalHeader().setMinimumSectionSize(55)
        self.tableWidget_27.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_27.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_27.verticalHeader().setVisible(False)
        self.tableWidget_27.verticalHeader().setDefaultSectionSize(55)
        self.tableWidget_27.verticalHeader().setMinimumSectionSize(55)
        self.tableWidget_28 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_28.setGeometry(QtCore.QRect(0, 140, 280, 280))
        self.tableWidget_28.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_28.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_28.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_28.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_28.setRowCount(5)
        self.tableWidget_28.setColumnCount(5)
        self.tableWidget_28.setObjectName("tableWidget_28")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_28.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_28.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_28.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_28.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_28.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_28.setHorizontalHeaderItem(2, item)
        self.tableWidget_28.horizontalHeader().setVisible(False)
        self.tableWidget_28.horizontalHeader().setDefaultSectionSize(55)
        self.tableWidget_28.horizontalHeader().setHighlightSections(True)
        self.tableWidget_28.horizontalHeader().setMinimumSectionSize(55)
        self.tableWidget_28.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_28.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_28.verticalHeader().setVisible(False)
        self.tableWidget_28.verticalHeader().setDefaultSectionSize(55)
        self.tableWidget_28.verticalHeader().setMinimumSectionSize(55)
        self.label_62 = QtWidgets.QLabel(self.tab_3)
        self.label_62.setGeometry(QtCore.QRect(300, 10, 160, 21))
        self.label_62.setObjectName("label_62")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(10, 110, 81, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(300, 110, 81, 16))
        self.label_12.setObjectName("label_12")
        self.spinBox_29 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_29.setGeometry(QtCore.QRect(190, 10, 70, 40))
        self.spinBox_29.setMinimum(1)
        self.spinBox_29.setMaximum(5)
        self.spinBox_29.setProperty("value", 5)
        self.spinBox_29.setObjectName("spinBox_29")
        self.spinBox_30 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_30.setGeometry(QtCore.QRect(500, 10, 70, 40))
        self.spinBox_30.setMinimum(1)
        self.spinBox_30.setMaximum(5)
        self.spinBox_30.setProperty("value", 5)
        self.spinBox_30.setObjectName("spinBox_30")
        self.label_63 = QtWidgets.QLabel(self.tab_3)
        self.label_63.setGeometry(QtCore.QRect(300, 30, 150, 21))
        self.label_63.setObjectName("label_63")
        self.spinBox_31 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_31.setGeometry(QtCore.QRect(190, 60, 70, 40))
        self.spinBox_31.setMaximum(5)
        self.spinBox_31.setProperty("value", 3)
        self.spinBox_31.setObjectName("spinBox_31")
        self.label_64 = QtWidgets.QLabel(self.tab_3)
        self.label_64.setGeometry(QtCore.QRect(10, 70, 160, 21))
        self.label_64.setObjectName("label_64")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(230, 450, 130, 40))
        self.pushButton_3.setCursor(Qt.PointingHandCursor)
        self.pushButton_3.setStyleSheet("""
                                                        QPushButton {
                                                            border: none;
                                                            color: rgb(80, 138, 198);
                                                            background-color: rgb(162, 208, 250);
                                                            border-radius:3px;}
                                                        QPushButton:hover {
                                                            background-color:  rgb(80, 138, 198);
                                                            color:  rgb(162, 208, 250);}
                                                            """)
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(230, 470, 130, 40))
        self.pushButton_4.setCursor(Qt.PointingHandCursor)
        self.pushButton_4.setStyleSheet("""
                                                        QPushButton {
                                                            border: none;
                                                            color: rgb(80, 138, 198);
                                                            background-color: rgb(162, 208, 250);
                                                            border-radius:3px;}
                                                        QPushButton:hover {
                                                            background-color:  rgb(80, 138, 198);
                                                            color:  rgb(162, 208, 250);}
                                                            """)
        self.pushButton_4.setObjectName("pushButton_4")
        self.tableWidget_29 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_29.setGeometry(QtCore.QRect(0, 560, 280, 280))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_29.sizePolicy().hasHeightForWidth())
        self.tableWidget_29.setSizePolicy(sizePolicy)
        self.tableWidget_29.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_29.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_29.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_29.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_29.setRowCount(5)
        self.tableWidget_29.setColumnCount(5)
        self.tableWidget_29.setObjectName("tableWidget_29")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_29.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_29.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_29.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_29.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_29.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_29.setHorizontalHeaderItem(2, item)
        self.tableWidget_29.horizontalHeader().setVisible(False)
        self.tableWidget_29.horizontalHeader().setDefaultSectionSize(55)
        self.tableWidget_29.horizontalHeader().setHighlightSections(True)
        self.tableWidget_29.horizontalHeader().setMinimumSectionSize(55)
        self.tableWidget_29.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_29.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_29.verticalHeader().setVisible(False)
        self.tableWidget_29.verticalHeader().setDefaultSectionSize(55)
        self.tableWidget_29.verticalHeader().setMinimumSectionSize(55)
        self.tableWidget_29.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.label_65 = QtWidgets.QLabel(self.tab)
        self.label_65.setGeometry(QtCore.QRect(10, 530, 81, 16))
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.tab)
        self.label_66.setGeometry(QtCore.QRect(10, 20, 200, 21))
        self.label_66.setObjectName("label_66")
        self.tableWidget_30 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_30.setGeometry(QtCore.QRect(0, 160, 280, 280))
        self.tableWidget_30.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_30.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_30.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_30.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_30.setRowCount(5)
        self.tableWidget_30.setColumnCount(5)
        self.tableWidget_30.setObjectName("tableWidget_30")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_30.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_30.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_30.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_30.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_30.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_30.setHorizontalHeaderItem(2, item)
        self.tableWidget_30.horizontalHeader().setVisible(False)
        self.tableWidget_30.horizontalHeader().setDefaultSectionSize(55)
        self.tableWidget_30.horizontalHeader().setHighlightSections(True)
        self.tableWidget_30.horizontalHeader().setMinimumSectionSize(55)
        self.tableWidget_30.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_30.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_30.verticalHeader().setVisible(False)
        self.tableWidget_30.verticalHeader().setDefaultSectionSize(55)
        self.tableWidget_30.verticalHeader().setMinimumSectionSize(55)
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(10, 130, 81, 16))
        self.label_13.setObjectName("label_13")
        self.spinBox_32 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_32.setGeometry(QtCore.QRect(230, 10, 70, 40))
        self.spinBox_32.setMinimum(1)
        self.spinBox_32.setMaximum(5)
        self.spinBox_32.setProperty("value", 5)
        self.spinBox_32.setObjectName("spinBox_32")
        self.label_68 = QtWidgets.QLabel(self.tab)
        self.label_68.setGeometry(QtCore.QRect(10, 80, 91, 21))
        self.label_68.setObjectName("label_68")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(120, 80, 171, 31))
        self.lineEdit.setObjectName("lineEdit")
        # Create a QIntValidator object with a range of -99 to 99
        validator = QIntValidator(-99,99)
        # Set the validator for the QLineEdit
        self.lineEdit.setValidator(validator)
        self.lineEdit.setStyleSheet("border: none;"
"margin-right: 3px;"
"margin-button:3px;"
"padding: 5px;"
"color: rgb(80, 138, 198);"
"background-color: rgb(162, 208, 250);"
"border-radius:3px;")
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_5.setGeometry(QtCore.QRect(230, 430, 130, 40))
        self.pushButton_5.setCursor(Qt.PointingHandCursor)
        self.pushButton_5.setStyleSheet("""
                                                        QPushButton {
                                                            border: none;
                                                            color: rgb(80, 138, 198);
                                                            background-color: rgb(162, 208, 250);
                                                            border-radius:3px;}
                                                        QPushButton:hover {
                                                            background-color:  rgb(80, 138, 198);
                                                            color:  rgb(162, 208, 250);}
                                                            """)
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_25 = QtWidgets.QLabel(self.tab_4)
        self.label_25.setGeometry(QtCore.QRect(60, 220, 101, 16))
        self.label_25.setStyleSheet("")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.label_69 = QtWidgets.QLabel(self.tab_4)
        self.label_69.setGeometry(QtCore.QRect(10, 500, 300, 16))
        self.label_69.setObjectName("label_69")

        self.label_71 = QtWidgets.QLabel(self.tab_4)
        self.label_71.setGeometry(QtCore.QRect(10, 20, 200, 21))
        self.label_71.setObjectName("label_71")
        self.tableWidget_32 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_32.setGeometry(QtCore.QRect(0, 100, 280, 280))
        self.tableWidget_32.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_32.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_32.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_32.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_32.setRowCount(5)
        self.tableWidget_32.setColumnCount(5)
        self.tableWidget_32.setObjectName("tableWidget_32")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_32.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_32.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_32.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_32.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_32.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_32.setHorizontalHeaderItem(2, item)
        self.tableWidget_32.horizontalHeader().setVisible(False)
        self.tableWidget_32.horizontalHeader().setDefaultSectionSize(55)
        self.tableWidget_32.horizontalHeader().setHighlightSections(True)
        self.tableWidget_32.horizontalHeader().setMinimumSectionSize(55)
        self.tableWidget_32.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_32.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_32.verticalHeader().setVisible(False)
        self.tableWidget_32.verticalHeader().setDefaultSectionSize(55)
        self.tableWidget_32.verticalHeader().setMinimumSectionSize(55)
        self.spinBox_34 = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_34.setGeometry(QtCore.QRect(230, 10, 70, 40))
        self.spinBox_34.setMinimum(1)
        self.spinBox_34.setMaximum(5)
        self.spinBox_34.setProperty("value", 5)
        self.spinBox_34.setObjectName("spinBox_34")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_6.setGeometry(QtCore.QRect(230, 430, 130, 40))
        self.pushButton_6.setCursor(Qt.PointingHandCursor)
        self.pushButton_6.setStyleSheet("""
                                                        QPushButton {
                                                            border: none;
                                                            color: rgb(80, 138, 198);
                                                            background-color: rgb(162, 208, 250);
                                                            border-radius:3px;}
                                                        QPushButton:hover {
                                                            background-color:  rgb(80, 138, 198);
                                                            color:  rgb(162, 208, 250);}
                                                            """)
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_72 = QtWidgets.QLabel(self.tab_5)
        self.label_72.setGeometry(QtCore.QRect(10, 20, 130, 21))
        self.label_72.setObjectName("label_72")
        self.spinBox_36 = QtWidgets.QSpinBox(self.tab_5)
        self.spinBox_36.setGeometry(QtCore.QRect(190, 10, 70, 40))
        self.spinBox_36.setMinimum(1)
        self.spinBox_36.setMaximum(5)
        self.spinBox_36.setProperty("value", 5)
        self.spinBox_36.setObjectName("spinBox_36")
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setGeometry(QtCore.QRect(10, 80, 81, 16))
        self.label_15.setObjectName("label_15")
        self.spinBox_37 = QtWidgets.QSpinBox(self.tab_5)
        self.spinBox_37.setGeometry(QtCore.QRect(500, 10, 70, 40))
        self.spinBox_37.setMinimum(1)
        self.spinBox_37.setMaximum(5)
        self.spinBox_37.setProperty("value", 5)
        self.spinBox_37.setObjectName("spinBox_37")
        self.tableWidget_33 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_33.setGeometry(QtCore.QRect(0, 110, 280, 280))
        self.tableWidget_33.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_33.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_33.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_33.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_33.setRowCount(5)
        self.tableWidget_33.setColumnCount(5)
        self.tableWidget_33.setObjectName("tableWidget_33")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_33.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_33.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_33.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_33.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_33.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_33.setHorizontalHeaderItem(2, item)
        self.tableWidget_33.horizontalHeader().setVisible(False)
        self.tableWidget_33.horizontalHeader().setDefaultSectionSize(55)
        self.tableWidget_33.horizontalHeader().setHighlightSections(True)
        self.tableWidget_33.horizontalHeader().setMinimumSectionSize(55)
        self.tableWidget_33.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_33.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_33.verticalHeader().setVisible(False)
        self.tableWidget_33.verticalHeader().setDefaultSectionSize(55)
        self.tableWidget_33.verticalHeader().setMinimumSectionSize(55)
        self.label_73 = QtWidgets.QLabel(self.tab_5)
        self.label_73.setGeometry(QtCore.QRect(10, 500, 81, 16))
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.tab_5)
        self.label_74.setGeometry(QtCore.QRect(300, 20, 150, 21))
        self.label_74.setObjectName("label_74")
        self.tableWidget_34 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_34.setGeometry(QtCore.QRect(0, 530, 280, 280))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_34.sizePolicy().hasHeightForWidth())
        self.tableWidget_34.setSizePolicy(sizePolicy)
        self.tableWidget_34.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_34.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_34.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_34.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_34.setRowCount(5)
        self.tableWidget_34.setColumnCount(5)
        self.tableWidget_34.setObjectName("tableWidget_34")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_34.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_34.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_34.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_34.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_34.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_34.setHorizontalHeaderItem(2, item)
        self.tableWidget_34.horizontalHeader().setVisible(False)
        self.tableWidget_34.horizontalHeader().setDefaultSectionSize(55)
        self.tableWidget_34.horizontalHeader().setHighlightSections(True)
        self.tableWidget_34.horizontalHeader().setMinimumSectionSize(55)
        self.tableWidget_34.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_34.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_34.verticalHeader().setVisible(False)
        self.tableWidget_34.verticalHeader().setDefaultSectionSize(55)
        self.tableWidget_34.verticalHeader().setMinimumSectionSize(55)
        self.tableWidget_34.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        # Create the button and set its parent to the QTabWidget
        self.button = QPushButton("Retour", self.tabWidget)
        self.button.setCursor(Qt.PointingHandCursor)
        self.button.setGeometry(QtCore.QRect(470, 800, 81, 16))
        self.button.setStyleSheet("""
                                                                QPushButton {
                                                                    border: none;
                                                                    color: rgb(80, 138, 198);
                                                                    background-color: rgb(162, 208, 250);
                                                                    border-radius:3px;}
                                                                QPushButton:hover {
                                                                    background-color:  rgb(80, 138, 198);
                                                                    color:  rgb(162, 208, 250);}
                                                                    """)
        # Set the button's fixed size
        self.button.setFixedHeight(50)
        self.button.setFixedWidth(100)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.tableWidget)
        MainWindow.setTabOrder(self.tableWidget, self.tableWidget_2)
        MainWindow.setTabOrder(self.tableWidget_2, self.tableWidget_3)
        MainWindow.setTabOrder(self.tableWidget_3, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.pushButton_6)

        # Connect the valueChanged signals to the update_matrix_size slot
        self.spinBox_14.valueChanged.connect(self.update_matrix_size_somme)
        self.spinBox_15.valueChanged.connect(self.update_matrix_size_somme)
        self.spinBox_27.valueChanged.connect(self.update_matrix_size_soustraction)
        self.spinBox_28.valueChanged.connect(self.update_matrix_size_soustraction)
        self.spinBox_32.valueChanged.connect(self.update_matrix_size_puissance)
        self.spinBox_34.valueChanged.connect(self.update_matrix_size_determinant)
        self.spinBox_36.valueChanged.connect(self.update_matrix_size_transpose)
        self.spinBox_37.valueChanged.connect(self.update_matrix_size_transpose)
        self.spinBox_29.valueChanged.connect(self.update_matrix_size_produit)
        self.spinBox_30.valueChanged.connect(self.update_matrix_size_produit)
        self.spinBox_31.valueChanged.connect(self.update_matrix_size_produit)
        self.pushButton.clicked.connect(self.calculer_somme)
        self.pushButton_11.clicked.connect(self.calculer_soustraction)
        self.pushButton_3.clicked.connect(self.calculer_produit)
        self.pushButton_4.clicked.connect(self.calculer_puissance)
        self.pushButton_5.clicked.connect(self.calculer_determinant)
        self.pushButton_6.clicked.connect(self.calculer_transpose)
        self.button.clicked.connect(self.calculatrice)
        self.button.clicked.connect(MainWindow.close)

    def update_matrix_size_somme(self):
        # Get the current values of the spin boxes
        rows = self.spinBox_14.value()
        cols = self.spinBox_15.value()

        # Update the size of the table widget
        self.tableWidget.setRowCount(rows)
        self.tableWidget.setColumnCount(cols)
        self.tableWidget_2.setRowCount(rows)
        self.tableWidget_2.setColumnCount(cols)
        self.tableWidget_3.setRowCount(rows)
        self.tableWidget_3.setColumnCount(cols)
        # Update the matrix size
        self.matrix = [[0] * cols for _ in range(rows)]
    def update_matrix_size_soustraction(self):
        # Get the current values of the spin boxes
        rows = self.spinBox_27.value()
        cols = self.spinBox_28.value()

        # Update the size of the table widget
        self.tableWidget_23.setRowCount(rows)
        self.tableWidget_23.setColumnCount(cols)
        self.tableWidget_24.setRowCount(rows)
        self.tableWidget_24.setColumnCount(cols)
        self.tableWidget_25.setRowCount(rows)
        self.tableWidget_25.setColumnCount(cols)
        # Update the matrix size
        self.matrix = [[0] * cols for _ in range(rows)]
    def update_matrix_size_produit(self):
        # Get the current values of the spin boxes
        rows = self.spinBox_29.value()
        cols = self.spinBox_30.value()
        cols2 = self.spinBox_31.value()

        # Update the size of the table widget
        self.tableWidget_28.setRowCount(rows)
        self.tableWidget_28.setColumnCount(cols)
        self.tableWidget_27.setRowCount(cols)
        self.tableWidget_27.setColumnCount(cols2)
        self.tableWidget_26.setRowCount(rows)
        self.tableWidget_26.setColumnCount(cols2)
        # Update the matrix size
        self.matrix = [[0] * cols for _ in range(rows)]
    def update_matrix_size_puissance(self):
        # Get the current values of the spin boxes
        rows = self.spinBox_32.value()

        # Update the size of the table widget
        self.tableWidget_29.setRowCount(rows)
        self.tableWidget_29.setColumnCount(rows)
        self.tableWidget_30.setRowCount(rows)
        self.tableWidget_30.setColumnCount(rows)
        # Update the matrix size
        self.matrix = [[0] * rows for _ in range(rows)]
    def update_matrix_size_determinant(self):
        # Get the current values of the spin boxes
        rows = self.spinBox_34.value()
        # Update the size of the table widget
        self.tableWidget_32.setRowCount(rows)
        self.tableWidget_32.setColumnCount(rows)
        # Update the matrix size
        self.matrix = [[0] * rows for _ in range(rows)]
    def update_matrix_size_transpose(self):
        # Get the current values of the spin boxes
        rows = self.spinBox_36.value()
        cols = self.spinBox_37.value()

        # Update the size of the table widget
        self.tableWidget_33.setRowCount(rows)
        self.tableWidget_33.setColumnCount(cols)
        self.tableWidget_34.setRowCount(cols)
        self.tableWidget_34.setColumnCount(rows)
        # Update the matrix size
        self.matrix = [[0] * cols for _ in range(rows)]

    def calculer_somme(self):

        def add_matrices(table1, table2):
            matrix1 = [[int(table1.item(i, j).text()) if table1.item(i, j) is not None else 0 for j in
                        range(table1.columnCount())] for i in range(table1.rowCount())]
            matrix2 = [[int(table2.item(i, j).text()) if table2.item(i, j) is not None else 0 for j in
                        range(table2.columnCount())] for i in range(table2.rowCount())]

            result = [[matrix1[i][j] + matrix2[i][j] for j in range(len(matrix1[i]))] for i in range(len(matrix1))]
            return result

        def display_result(result, table):
            for i in range(len(result)):
                for j in range(len(result[i])):
                    item = QTableWidgetItem(str(result[i][j]))
                    table.setItem(i, j, item)

        if table_contains_noninteger_values(self.tableWidget) or table_contains_noninteger_values(self.tableWidget_2):
            return
        result = add_matrices(self.tableWidget, self.tableWidget_2)
        display_result(result, self.tableWidget_3)

    def calculer_soustraction(self):
        def subtract_matrices(table1, table2):
            matrix1 = [[int(table1.item(i, j).text()) if table1.item(i, j) is not None else 0 for j in
                        range(table1.columnCount())] for i in range(table1.rowCount())]
            matrix2 = [[int(table2.item(i, j).text()) if table2.item(i, j) is not None else 0 for j in
                        range(table2.columnCount())] for i in range(table2.rowCount())]

            result = [[matrix1[i][j] - matrix2[i][j] for j in range(len(matrix1[i]))] for i in range(len(matrix1))]
            return result

        def display_result(result, table):
            for i in range(len(result)):
                for j in range(len(result[i])):
                    item = QTableWidgetItem(str(result[i][j]))
                    table.setItem(i, j, item)
        if table_contains_noninteger_values(self.tableWidget_25) or table_contains_noninteger_values(self.tableWidget_24):
            return
        result = subtract_matrices(self.tableWidget_25, self.tableWidget_24)
        display_result(result, self.tableWidget_23)
    def calculer_produit(self):
        def matrix_multiply(matrix1, matrix2):
            result = [[0 for j in range(len(matrix2[0]))] for i in range(len(matrix1))]

            for i in range(len(matrix1)):
                for j in range(len(matrix2[0])):
                    for k in range(len(matrix2)):
                        result[i][j] += matrix1[i][k] * matrix2[k][j]
            return result

        def get_matrix_from_table(table):
            matrix = [[int(table.item(i, j).text()) if table.item(i, j) is not None else 0 for j in
                       range(table.columnCount())] for i in range(table.rowCount())]
            return matrix

        def display_result(result, table):
            for i in range(len(result)):
                for j in range(len(result[i])):
                    item = QTableWidgetItem(str(result[i][j]))
                    table.setItem(i, j, item)
        if table_contains_noninteger_values(self.tableWidget_28) or table_contains_noninteger_values(self.tableWidget_27):
            return
        matrix1 = get_matrix_from_table(self.tableWidget_28)
        matrix2 = get_matrix_from_table(self.tableWidget_27)
        result = matrix_multiply(matrix1, matrix2)
        display_result(result, self.tableWidget_26)

    def calculer_puissance(self):
        exponent = int(self.lineEdit.text())
        if table_contains_noninteger_values(self.tableWidget_30):
            return
        # Get the matrix from the table
        rows = self.spinBox_36.value()
        cols = self.spinBox_37.value()
        matrix = np.zeros((rows, cols))
        for i in range(rows):
            for j in range(cols):
                item = self.tableWidget_30.item(i, j)
                if item is not None:
                    matrix[i, j] = int(item.text())

        # Raise the matrix to the specified power
        result = np.linalg.matrix_power(matrix, exponent)
        # Update the table with the result
        for i in range(rows):
            for j in range(cols):
                item = QTableWidgetItem(str(result[i, j]))
                self.tableWidget_29.setItem(i, j, item)

    def calculer_determinant(self):
        self.label_69.setText("Determinant =     ")
        # Get the matrix from the input table
        if table_contains_noninteger_values(self.tableWidget_32):
            return
        rows = self.spinBox_34.value()
        matrix = np.zeros((rows, rows))
        for i in range(rows):
            for j in range(rows):
                item = self.tableWidget_32.item(i, j)
                if item is not None:
                    matrix[i, j] = int(item.text())

        # Calculate the determinant of the matrix
        determinant = np.linalg.det(matrix)

        # Update the output with the result
        text = self.label_69.text()
        self.label_69.setText(text + str(round(determinant)))
    def calculer_transpose(self):
        if table_contains_noninteger_values(self.tableWidget_33):
            return
        def calculate_transpose(input_table, output_table):
            rows = self.spinBox_36.value()
            cols = self.spinBox_37.value()
            # Iterate through the cells of the input table and set the transposed values in the output table
            for i in range(rows):
                for j in range(cols):
                    item = input_table.item(i, j)
                    if item is not None:
                        value = int(item.text())
                        output_item = QTableWidgetItem(str(value))
                        output_table.setItem(j, i, output_item)
        calculate_transpose(self.tableWidget_33, self.tableWidget_34)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calcul matriciel"))
        icon = QIcon("logo.png")
        MainWindow.setWindowIcon(icon)
        self.label_3.setText(_translate("MainWindow", "Matrice 1 :"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        self.label_4.setText(_translate("MainWindow", "Matrice 2 :"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        self.label_5.setText(_translate("MainWindow", "Résult :"))
        self.pushButton.setText(_translate("MainWindow", "Calculer"))
        self.label_32.setText(_translate("MainWindow", "Nombre de ligne :"))
        self.label_33.setText(_translate("MainWindow", "Nombre de colonne :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Somme"))
        self.label_57.setText(_translate("MainWindow", "Nombre de colonne :"))
        item = self.tableWidget_23.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_23.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_23.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_23.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_23.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_23.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        self.label_9.setText(_translate("MainWindow", "Matrice 1 :"))
        self.label_10.setText(_translate("MainWindow", "Matrice 2 :"))
        self.label_58.setText(_translate("MainWindow", "Résult :"))
        self.label_59.setText(_translate("MainWindow", "Nombre de ligne :"))
        item = self.tableWidget_24.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_24.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_24.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_24.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_24.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_24.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_25.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_25.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_25.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_25.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_25.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_25.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        self.pushButton_11.setText(_translate("MainWindow", "Calculer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Soustraction"))
        item = self.tableWidget_26.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_26.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_26.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_26.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_26.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_26.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        self.label_60.setText(_translate("MainWindow", "Résult :"))
        self.label_61.setText(_translate("MainWindow", "N° de ligne de M1 :"))
        item = self.tableWidget_27.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_27.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_27.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_27.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_27.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_27.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_28.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_28.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_28.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_28.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_28.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_28.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        self.label_62.setText(_translate("MainWindow", "N° de colonne de M1 :"))
        self.label_11.setText(_translate("MainWindow", "Matrice 1 :"))
        self.label_12.setText(_translate("MainWindow", "Matrice 2 :"))
        self.label_63.setText(_translate("MainWindow", "(N° de ligne de M2)"))
        self.label_64.setText(_translate("MainWindow", "N° de colonne de M2 :"))
        self.pushButton_3.setText(_translate("MainWindow", "Calculer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Produit"))
        self.pushButton_4.setText(_translate("MainWindow", "Calculer"))
        item = self.tableWidget_29.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_29.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_29.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_29.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_29.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_29.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        self.label_65.setText(_translate("MainWindow", "Résult :"))
        self.label_66.setText(_translate("MainWindow", "N° de ligne et de colonne :"))
        item = self.tableWidget_30.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_30.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_30.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_30.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_30.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_30.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        self.label_13.setText(_translate("MainWindow", "Matrice :"))
        self.label_68.setText(_translate("MainWindow", "Puissance :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Puissance"))
        self.pushButton_5.setText(_translate("MainWindow", "Calculer"))
        self.label_69.setText(_translate("MainWindow", "Determinant =     "))
        self.label_71.setText(_translate("MainWindow", "N° de ligne et de colonne :"))
        item = self.tableWidget_32.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_32.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_32.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_32.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_32.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_32.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        self.label_14.setText(_translate("MainWindow", "Matrice :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Determinant"))
        self.pushButton_6.setText(_translate("MainWindow", "Calculer"))
        self.label_72.setText(_translate("MainWindow", "Nombre de ligne :"))
        self.label_15.setText(_translate("MainWindow", "Matrice :"))
        item = self.tableWidget_33.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_33.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_33.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_33.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_33.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_33.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        self.label_73.setText(_translate("MainWindow", "Résult :"))
        self.label_74.setText(_translate("MainWindow", "Nombre de colonne :"))
        item = self.tableWidget_34.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_34.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_34.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_34.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_34.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_34.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Transposé"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = MatriceWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
